"use strict";
/* based on ORSCF SubjectData Contract v1.8.0.0 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.SubjectMutation = exports.BatchableSubjectMutation = exports.SubjectFhirRessourceContainer = exports.SubjectStructure = exports.SubjectFields = exports.CustomFieldDescriptor = exports.SubjectMetaRecord = exports.SubjectFilter = void 0;
var SubjectFilter = /** @class */ (function () {
    function SubjectFilter() {
    }
    return SubjectFilter;
}());
exports.SubjectFilter = SubjectFilter;
var SubjectMetaRecord = /** @class */ (function () {
    function SubjectMetaRecord() {
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        this.subjectUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        this.subjectIdentifier = '';
        this.studyUid = '';
        this.actualSiteUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        this.modificationTimestampUtc = 0;
    }
    return SubjectMetaRecord;
}());
exports.SubjectMetaRecord = SubjectMetaRecord;
var CustomFieldDescriptor = /** @class */ (function () {
    function CustomFieldDescriptor() {
        this.technicalName = '';
        this.isRequired = false;
        this.displayLabel = '';
    }
    return CustomFieldDescriptor;
}());
exports.CustomFieldDescriptor = CustomFieldDescriptor;
var SubjectFields = /** @class */ (function (_super) {
    __extends(SubjectFields, _super);
    function SubjectFields() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.enrollingSiteUid = '';
        /**
         * AS DECLARED BY [HL7.ResearchSubjectStatus](https://www.hl7.org/fhir/valueset-research-subject-status.html): candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
         */
        _this.status = '';
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.subjectUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        _this.subjectIdentifier = '';
        _this.studyUid = '';
        _this.actualSiteUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return SubjectFields;
}(SubjectMetaRecord));
exports.SubjectFields = SubjectFields;
var SubjectStructure = /** @class */ (function (_super) {
    __extends(SubjectStructure, _super);
    function SubjectStructure() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        _this.enrollingSiteUid = '';
        /**
         * AS DECLARED BY [HL7.ResearchSubjectStatus](https://www.hl7.org/fhir/valueset-research-subject-status.html): candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
         */
        _this.status = '';
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.subjectUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        _this.subjectIdentifier = '';
        _this.studyUid = '';
        _this.actualSiteUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return SubjectStructure;
}(SubjectFields));
exports.SubjectStructure = SubjectStructure;
/**
 * A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
 */
var SubjectFhirRessourceContainer = /** @class */ (function (_super) {
    __extends(SubjectFhirRessourceContainer, _super);
    function SubjectFhirRessourceContainer() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.subjectUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        _this.subjectIdentifier = '';
        _this.studyUid = '';
        _this.actualSiteUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return SubjectFhirRessourceContainer;
}(SubjectMetaRecord));
exports.SubjectFhirRessourceContainer = SubjectFhirRessourceContainer;
var BatchableSubjectMutation = /** @class */ (function () {
    function BatchableSubjectMutation() {
    }
    return BatchableSubjectMutation;
}());
exports.BatchableSubjectMutation = BatchableSubjectMutation;
var SubjectMutation = /** @class */ (function (_super) {
    __extends(SubjectMutation, _super);
    function SubjectMutation() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return SubjectMutation;
}(BatchableSubjectMutation));
exports.SubjectMutation = SubjectMutation;
//# sourceMappingURL=models.js.map